use serde::{Deserialize, Serialize};

use cosh_tui::core::lib::rgba::RGBA;

use crate::theme::Theme;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Session {
    pub id: String,
    pub title: String,
    pub messages: Vec<Message>,
    /// Unix timestamp in milliseconds when the session was created.
    pub created_at: u64,
    /// Whether the title was generated by the LLM.
    pub title_generated: bool,
    /// Provider of the last model used in this session. Persisted in the
    /// session header so the model is restored when the session is reopened.
    pub provider: Option<String>,
    /// The last model used in this session. Persisted in the session header.
    pub model: Option<String>,
    /// Reasoning effort (`None` = model default) for the last model used in
    /// this session. Persisted in the session header.
    pub reasoning: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    pub id: String,
    pub role: MessageRole,
    pub parts: Vec<Part>,
    pub created_at: u64,
    pub agent: Option<String>,
    pub model: Option<String>,
}

impl Message {
    /// Append a reasoning delta while keeping all reasoning contiguous and
    /// ordered before the visible answer. If the answer (a `Text` part) has
    /// already started streaming, the delta is folded back into the last
    /// `Reasoning` part that precedes it instead of spawning a new Thought
    /// block after the answer.
    pub fn push_reasoning(&mut self, text: &str) {
        if let Some(text_idx) = self.parts.iter().position(|p| matches!(p, Part::Text(_))) {
            match (0..text_idx)
                .rev()
                .find(|&i| matches!(self.parts[i], Part::Reasoning(_)))
            {
                Some(i) => {
                    if let Part::Reasoning(rp) = &mut self.parts[i] {
                        rp.text.push_str(text);
                    }
                }
                None => self.parts.insert(
                    text_idx,
                    Part::Reasoning(ReasoningPart {
                        text: text.to_string(),
                        collapsed: true,
                    }),
                ),
            }
        } else if matches!(self.parts.last(), Some(Part::Reasoning(_))) {
            if let Some(Part::Reasoning(rp)) = self.parts.last_mut() {
                rp.text.push_str(text);
            }
        } else {
            self.parts.push(Part::Reasoning(ReasoningPart {
                text: text.to_string(),
                collapsed: true,
            }));
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum MessageRole {
    User,
    Assistant,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Part {
    Text(TextPart),
    Tool(ToolPart),
    Reasoning(ReasoningPart),
    File(FilePart),
    /// A context-compaction status line (pipeline stopwatch / phase notice).
    Compaction(CompactionPart),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TextPart {
    pub text: String,
    pub synthetic: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolPart {
    pub tool: String,
    pub input: serde_json::Value,
    pub output: Option<String>,
    pub status: ToolStatus,
    pub tool_call_id: Option<String>,
    pub is_start: bool,
    pub is_streaming: bool,
    /// Cached line count for streaming tools (glob/grep) to avoid O(n) recounting
    #[serde(skip)]
    pub cached_line_count: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolStatus {
    Running,
    Completed,
    Failed(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReasoningPart {
    pub text: String,
    pub collapsed: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilePart {
    pub filename: String,
    pub mime: String,
}

/// A context-compaction status line in the chat: the LLM "Summarizing" box.
/// Persisted with the session like any other part.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompactionPart {
    /// Which compaction phase this line reports (always [`CompactionPhase::Llm`]).
    pub phase: CompactionPhase,
    /// Wall-clock unix millis when the phase started (persisted so a restored
    /// session can still show a coherent elapsed time).
    pub started_at: u64,
    /// Final elapsed millis when the phase finished; `None` while running.
    pub elapsed_ms: Option<u64>,
    /// The streamed text of the summarizer: the tokens accumulate here and the
    /// "Summarizing" box renders them (collapsed = bounded preview that
    /// visually scrolls up, expanded = full growing body).
    #[serde(default)]
    pub text: String,
}

/// The only context-compaction phase a [`CompactionPart`] reports: the LLM
/// compaction (the last-resort fallback, driven by the harness). The model call
/// can take seconds, so its line carries a live stopwatch.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CompactionPhase {
    Llm,
}

impl CompactionPart {
    /// A fresh running phase line (stopwatch active).
    pub fn running(phase: CompactionPhase) -> Self {
        Self {
            phase,
            started_at: now_ms(),
            elapsed_ms: None,
            text: String::new(),
        }
    }

    pub fn is_running(&self) -> bool {
        self.elapsed_ms.is_none()
    }
}

/// Current wall-clock time in unix milliseconds (used by the stopwatch).
pub fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SessionStatus {
    Idle,
    Working,
    Retry {
        message: String,
        action: Option<serde_json::Value>,
    },
}

pub struct AgentColors {
    palette: Vec<RGBA>,
}

impl AgentColors {
    pub fn from_theme(theme: &Theme) -> Self {
        Self {
            palette: vec![
                theme.secondary,
                theme.accent,
                theme.success,
                theme.warning,
                theme.primary,
                theme.error,
                theme.info,
            ],
        }
    }

    pub fn get(&self, name: &str, unique_agents: &[String]) -> RGBA {
        let index = unique_agents.iter().position(|a| a == name).unwrap_or(0);
        self.palette[index % self.palette.len()]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn msg() -> Message {
        Message {
            id: "m".into(),
            role: MessageRole::Assistant,
            parts: vec![],
            created_at: 0,
            agent: None,
            model: None,
        }
    }

    fn reasoning(text: &str) -> Part {
        Part::Reasoning(ReasoningPart {
            text: text.to_string(),
            collapsed: true,
        })
    }

    fn text(text: &str) -> Part {
        Part::Text(TextPart {
            text: text.to_string(),
            synthetic: false,
        })
    }

    fn tool() -> Part {
        Part::Tool(ToolPart {
            tool: "read".into(),
            input: serde_json::json!({}),
            output: None,
            status: ToolStatus::Running,
            tool_call_id: None,
            is_start: true,
            is_streaming: false,
            cached_line_count: None,
        })
    }

    #[test]
    fn reasoning_after_answer_folds_back_into_prior_thought() {
        let mut m = msg();
        m.push_reasoning("R1");
        m.parts.push(text("T1"));
        m.push_reasoning("R2");
        // Mirror the Token handler: append to the trailing text part.
        if let Some(Part::Text(t)) = m.parts.last_mut() {
            t.text.push_str("T2");
        } else {
            m.parts.push(text("T2"));
        }

        assert_eq!(m.parts.len(), 2);
        match (&m.parts[0], &m.parts[1]) {
            (Part::Reasoning(r), Part::Text(t)) => {
                assert_eq!(r.text, "R1R2");
                assert_eq!(t.text, "T1T2");
            }
            other => panic!("expected [Reasoning, Text], got {other:?}"),
        }
    }

    #[test]
    fn reasoning_between_tool_calls_stays_separate() {
        let mut m = msg();
        m.push_reasoning("R1");
        m.parts.push(tool());
        m.push_reasoning("R2");

        assert_eq!(m.parts.len(), 3);
        assert!(matches!(m.parts[0], Part::Reasoning(_)));
        assert!(matches!(m.parts[1], Part::Tool(_)));
        match &m.parts[2] {
            Part::Reasoning(r) => assert_eq!(r.text, "R2"),
            other => panic!("expected trailing Reasoning, got {other:?}"),
        }
    }

    #[test]
    fn reasoning_after_answer_without_prior_thought_inserts_before_text() {
        let mut m = msg();
        m.parts.push(text("T1"));
        m.push_reasoning("R1");

        assert_eq!(m.parts.len(), 2);
        assert!(matches!(m.parts[0], Part::Reasoning(_)));
        assert!(matches!(m.parts[1], Part::Text(_)));
        match &m.parts[0] {
            Part::Reasoning(r) => assert_eq!(r.text, "R1"),
            other => panic!("expected Reasoning before text, got {other:?}"),
        }
    }

    #[test]
    fn consecutive_reasoning_appends_to_trailing_thought() {
        let mut m = msg();
        m.push_reasoning("R1");
        m.push_reasoning("R2");

        assert_eq!(m.parts.len(), 1);
        match &m.parts[0] {
            Part::Reasoning(r) => assert_eq!(r.text, "R1R2"),
            other => panic!("expected single Reasoning, got {other:?}"),
        }
    }
}
