[package]
name = "cosh-server"
version = "0.1.0"
edition = "2024"

[dependencies.cosh-sdk]
path = "../crates/cosh-sdk"

[dependencies.cosh-tools]
path = "../crates/cosh-tools"

[dependencies]
anyhow = "1"
schemars = "1"

[dependencies.serde_json]
version = "1"

[dependencies.ratatui]
version = "0.30.2"
default-features = false
features = []

# ---
[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.rmcp]
version = "1.8.0"
features = ["server", "transport-io"]

[dependencies.serde]
version = "1"
features = ["derive"]

[lints]
workspace = true
