[package]
edition = "2024"
name = "cosh-sdk"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globset = "0.4.18"
grep-matcher = "0.1.8"
grep-regex = "0.1.14"
grep-searcher = "0.1.16"
ignore = "0.4.25"
libc = "0.2"
log = "0.4"
lru = "0.12"
memmap2 = "0.9.9"
miniz_oxide = "0.8"
rayon = "1"
regex = "1"
serde_json = "1.0.150"
similar = "3.1.1"
smallvec = "1"
tree-sitter = "0.26.9"
tree-sitter-c-sharp = "0.23"
tree-sitter-go = "0.25"
tree-sitter-haskell = "0.23"
tree-sitter-java = "0.23"
tree-sitter-javascript = "0.25"
tree-sitter-python = "0.25"
tree-sitter-rust = "0.24"
tree-sitter-swift = "0.7"
tree-sitter-zig = "1.1"
tree-sitter-kotlin = "0.4"
xxhash-rust = { version = "0.8", features = ["xxh32"] }
tokio = { version = "1.52.3", features = ["full"] }
async-stream = "0.3"
tokio-stream = "0.1"
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }

# term_screen dependencies
base64 = "0.22"
bitflags = { version = "2", features = ["serde"] }
csscolorparser = "0.7"
downcast-rs = "1.2"
hex = "0.4"
finl_unicode = "1.3"
fixedbitset = { version = "0.5", features = ["serde"] }
lazy_static = "1.5"
num-derive = "0.4"
num-traits = "0.2"
ordered-float = { version = "4.5", features = ["serde"] }
siphasher = "1.0"
terminfo = "0.9"
thiserror = "2"
unicode-normalization = "0.1"
unicode-segmentation = "1.12"
unicode-width = "0.2"
url = "2.5"
vtparse = "0.7"

[dev-dependencies]
env_logger = "0.11"
insta = { version = "1", features = ["filters"] }
serial_test = "3"
