[package]
edition = "2021"
name = "cosh-sdk"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lru = "0.12"
regex = "1"
similar = "3.1.1"
log = "0.4"
xxhash-rust = { version = "0.8", features = ["xxh32"] }
tokio = { version = "1.52.3", features = ["full"] }
tree-sitter = "0.26.9"
tree-sitter-rust = "0.24"
tree-sitter-python = "0.25"
tree-sitter-javascript = "0.25"
tree-sitter-c-sharp = "0.23"
tree-sitter-go = "0.25"
tree-sitter-java = "0.23"
tree-sitter-haskell = "0.23"
tree-sitter-swift = "0.7"
tree-sitter-zig = "1.1"
# tree-sitter-kotlin = "0.3.8"
